#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.6.6

pipelines:
  default:
      - step:
          name: Swagger
          script:
            - export DATABASE_URL="postgres://hctwqjbrvcsgma:62ec456ec10405cc7691530aa392118fa0e01af0f2bbf97f188dba6689e6dc0d@ec2-54-228-209-117.eu-west-1.compute.amazonaws.com:5432/d1jnti2aeegab7"
            - gem install bundler:2.2.8
            - bundle install
            - bundle exec rake rswag
            - git remote set-url origin http://bitbucket.org/e-city/mvms-api
            - git status
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json"
            - git push


