#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.6.6

pipelines:
  default:
      - step:
          name: Swagger
          script:
            - gem install bundler:2.2.8
            - bundle install
            - bundle exec rake rswag
