#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.6.6

pipelines:
  branches:
    dev:
      - step:
          name: Swagger
          script:
            - export BASE_URL="https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-dev"
            - gem install bundler:2.2.16
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json"
            - git pull
            - git push
    release/v*:
      - step:
          name: Swagger
          script:
            - export BASE_URL="https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-staging"
            - gem install bundler:2.2.16
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json"
            - git pull
            - git push
    hotfix/v*:
      - step:
          name: Swagger
          script:
            - export BASE_URL="https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-staging"
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - gem install bundler:2.2.16
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json"
            - git pull
            - git push
    master:
      - step:
          name: Swagger
          script:
            - export BASE_URL="https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog"
            - gem install bundler:2.2.16
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json"
            - git pull
            - git push

