#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.6.6

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - export DATABASE_URL="postgres://ue1rgleac2brfs:pd2aece2fa947c8901d06f32fbf7c0daef02712bfc10faec1a563f3f5fbc3999e@ec2-54-74-206-102.eu-west-1.compute.amazonaws.com:5432/d88qcna1ceab3j"
            - export API_BASE_URL=`{ case $BITBUCKET_PR_DESTINATION_BRANCH in dev) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-dev" ;; release/v*) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-staging" ;; master) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog" ;; esac }`
            - gem install bundler:2.2.16
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json" || true
            - git pull
            - git push
