#  Template Ruby build

#  This template allows you to validate your Ruby code.
#  The workflow allows running tests and code linting on the default branch.

image: ruby:2.6.6

pipelines:
  pull-requests:
    "**":
      - step:
          script:
            - export DATABASE_URL="postgres://hctwqjbrvcsgma:62ec456ec10405cc7691530aa392118fa0e01af0f2bbf97f188dba6689e6dc0d@ec2-54-228-209-117.eu-west-1.compute.amazonaws.com:5432/d1jnti2aeegab7"
            - export BASE_URL=`{ case $BITBUCKET_PR_DESTINATION_BRANCH in dev) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-dev" ;; release/v*) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog-staging" ;; master) echo "https://stingy-advice-gw.aws-euc1.cloud-ara.tyk.io/catalog" ;; esac }`
            - gem install bundler:2.2.16
            - bundle config https://gem.fury.io/mvms/ 1NRAu1-s5LftEnpweDkWewfASsrNMbVmaQ
            - bundle install
            - bundle exec rake rswag PATTERN="spec/swagger/**/*_spec.rb"
            - git add swagger/v1/swagger.json
            - git commit -m "[skip ci] Bitbucket pipelines - update swagger.json" || true
            - git pull
            - git push
