get ":shop_id/products", to: "products#index"
get ":shop_id/products/:id", to: "products#show"
post ":shop_id/products", to: "products#create"
post ":shop_id/products/offline", to: "products#create_offline"
put ":shop_id/products/:id", to: "products#update"
put ":shop_id/products/:id/offline", to: "products#update_offline"
delete ":shop_id/products/:id", to: "products#destroy"
delete ":shop_id/products/:id/offline", to: "products#destroy_offline"
