---
:concurrency: 3
staging:
  :concurrency: 3
production:
  :concurrency: 10
:queues:
  - critical
  - very-high
  - high
  - mailers
  - medium-hight
  - medium
  - medium-low
  - default
  - low
  - very-low