require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is gene^rated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::Shops::Products::ImagesController, type: :controller do
  describe "DELETE #destroy" do
    before(:all) do
      @user_shop_employee = create(:shop_employee_user)
      @product = create(:available_product)
      @reference = @product.references.first
      @sample = @reference.sample
      @shop = @product.shop
      @user_shop_employee.shop_employee.shops << @product.shop
    end
    after(:all) do
      @user_shop_employee.destroy
      @shop.products.destroy_all
      @shop.destroy
    end

    context 'All ok' do
      it "should return http status 204 and destroy the image" do
        image = create(:image)
        @sample.images << image
        request.headers['x-client-id'] = generate_token(@user_shop_employee)
        delete :destroy, params: { product_id: @product.id, id: image.id }
        expect(response).to have_http_status(204)
        expect(Image.where(id: image.id).first).to eq(nil)
      end
    end

    context "Errors" do
      context "Bad product status" do
        before(:all) do
          @product_bad = create(:available_product, shop: @shop)
          @reference_bad = @product.references.first
          @sample_bad = @reference.sample
          @shop_bad = @product.shop
          @user_shop_employee.shop_employee.shops << @product.shop
        end
        context "Product has draft_cityzen status" do
          it "should return HTTP status 403" do
            image = create(:image)
            @product_bad.update!(status: :draft_cityzen)
            @sample_bad.images << image
            request.headers['x-client-id'] = generate_token(@user_shop_employee)
            delete :destroy, params: { product_id: @product_bad.id, id: image.id }
            expect(response).to have_http_status(403)
            expect(response.body).to eq(Dto::Errors::Forbidden.new.to_h.to_json)
          end
        end

        context "Product has refused status" do
          it "should return HTTP status 403" do
            image = create(:image)
            @product_bad.update!(status: :refused)
            @sample_bad.images << image
            request.headers['x-client-id'] = generate_token(@user_shop_employee)
            delete :destroy, params: { product_id: @product_bad.id, id: image.id }
            expect(response).to have_http_status(403)
            expect(response.body).to eq(Dto::Errors::Forbidden.new.to_h.to_json)
          end
        end
      end
      context 'Not found' do
        context "when image didn't exit" do
          it "should return HTTP status 404" do
            image = create(:image)
            @sample.images << image
            image.destroy
            request.headers['x-client-id'] = generate_token(@user_shop_employee)
            delete :destroy, params: { product_id: @product.id, id: image.id }
            expect(response).to have_http_status(404)
            expect(response.body).to eq(Dto::Errors::NotFound.new("Could not find Image with id: #{image.id} for product_id: #{@product.id}").to_h.to_json)
          end
        end
      end

      context "Bad Authentication" do
        context "without x-client-id" do
          it "should respond with HTTP STATUS 401" do
            delete :destroy, params: { product_id: 0, id: 0 }
            expect(response).to have_http_status(401)
            expect(response.body).to eq(Dto::Errors::Unauthorized.new.to_h.to_json)
          end
        end
      end

      context "Bad Authorization" do

        context "when user is a customer" do
          it "should respond with HTTP STATUS 403" do
            request.headers['x-client-id'] = generate_token(create(:customer_user))
            delete :destroy, params: { product_id: 0, id: 0 }
            expect(response).to have_http_status(403)
            expect(response.body).to eq(Dto::Errors::Forbidden.new.to_h.to_json)
          end
        end

        context "when user is a admin" do
          it "should respond with HTTP STATUS 403" do
            request.headers['x-client-id'] = generate_token(create(:admin_user))
            delete :destroy, params: { product_id: 0, id: 0 }
            expect(response).to have_http_status(403)
            expect(response.body).to eq(Dto::Errors::Forbidden.new.to_h.to_json)
          end
        end
      end
    end
  end
end


