require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is gene^rated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Api::V1::Shops::ProductsController, type: :controller do

  # GET #index
  describe "GET #index" do
    context "with valid params" do
      context 'without filters' do
        it "get all products from shop by position default" do
          products = [
            create(:product, status: "online", position: 1),
            create(:product, status: "online", position: 2),
            create(:product, status: "offline")
          ]
          shop = create(:shop)
          products.each { |prod| prod.update(shop_id: shop.id) }

          online_products = Product.where(status: "online").sort_by(&:position)

          allow(Product).to receive(:search).and_return(online_products)
          get :index, params: { id: shop.id }
          should respond_with(200)

          response_body = JSON.parse(response.body)
          expect(response_body).to be_an_instance_of(Array)
          expect(response_body.count).to eq(2)

          product_ids = response_body.map { |p| p.symbolize_keys[:id] }
          expect(Product.where(id: product_ids).to_a).to eq(online_products)
        end

        it 'get products matching query' do
          products = [
            create(:available_product, name: 'patator', status: "online"),
            create(:available_product, name: 'koup-koup', status: "online"),
            create(:available_product, name: 'tromblon', status: "online"),
            create(:available_product, name: 'coutelas', status: "online"),
            create(:available_product, name: 'coutelas de loup de mer', status: "online"),
            create(:available_product, name: 'coutelas de flibustier', status: "online")
          ]
          shop = create(:shop)
          products.each { |prod| prod.update(shop_id: shop.id) }

          products_to_return = Product.where('name like ?', '%coutelas%')

          allow(Product).to receive(:search).and_return(products_to_return)
          get :index, params: { id: shop.id, query: 'coutelas' }
          should respond_with(200)

          response_body = JSON.parse(response.body)
          expect(response_body).to be_an_instance_of(Array)
          expect(response_body.count).to eq(3)
          expect(response_body.pluck('name')).to eq(products_to_return.pluck('name'))
        end

        it 'handles pagination' do
          shop = create(:shop)
          products = []
          30.times do
            products << create(:product, status: "online", shop_id: shop.id)
          end

          products_to_return = products.dup.last(15)

          allow(Product).to receive(:search).and_return(products_to_return.to_a)

          get :index, params: { id: shop.id, page: 2}
          should respond_with(200)
          response_body = JSON.parse(response.body)
          expect(response_body).to be_an_instance_of(Array)
          expect(response_body.count).to eq(15)
          expect(response_body.pluck('id')).not_to eq(products.first(15).map(&:id))
        end
      end

      context 'with categories filters' do
        context 'with one category slug' do
          it 'return array of products with the relevant category' do
            weapon_cat = create(:category, name: 'Arme')
            long_range_cat = create(:category, name: 'Longue portée', parent_id: weapon_cat.id)
            veggie_cat = create(:category, name: 'Végétarienne', parent_id: long_range_cat.id)
            products = [
              create(:product, name: 'patator', status: "online", category_id: veggie_cat.id),
              create(:product, status: "online", ),
              create(:product, status: "offline")
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            product_to_return = Product.where(status: "online", name: 'patator', category_id: veggie_cat.id)

            allow(Product).to receive(:search).and_return(product_to_return.to_a)

            get :index, params: { id: shop.id, categories: veggie_cat.slug }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(1)
          end
        end

        context 'with several category slugs' do
          it 'return array of products with the relevant category' do
            weapon_cat = create(:category, name: 'Arme')
            long_range_cat = create(:category, name: 'Longue portée', parent_id: weapon_cat.id)
            short_range_cat = create(:category, name: 'Courte portée', parent_id: weapon_cat.id)
            veggie_cat = create(:category, name: 'Végétarienne', parent_id: long_range_cat.id)
            meatty_cat = create(:category, name: 'Carnivore', parent_id: short_range_cat.id)

            products = [
              create(:product, name: 'patator', status: "online", category_id: veggie_cat.id),
              create(:product, name: 'koup-koup', status: "online", category_id: meatty_cat.id),
              create(:product, status: "online")
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products_to_return = Product.where(name: ["patator", "koup-koup"])

            allow(Product).to receive(:search).and_return(products_to_return.to_a)

            get :index, params: { id: shop.id, categories: "#{veggie_cat.slug}__#{meatty_cat.slug}" }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(2)
          end
        end
      end

      context 'with prices filters' do
        it 'returns array of products with prices inside params range' do
          products = [
            create(:available_product, name: 'patator', status: "online"),
            create(:available_product, name: 'koup-koup', status: "online"),
            create(:available_product, name: 'tromblon', status: "online"),
            create(:available_product, name: 'coutelas', status: "online")
          ]
          shop = create(:shop)
          products.each { |prod| prod.update(shop_id: shop.id) }
          products_to_return = products.first(2).each { |prod| prod.references.first.update(base_price: rand(101..2000))}
          products.last.references.first.update(base_price: 3000)

          allow(Product).to receive(:search).and_return(products_to_return.to_a)
          get :index, params: { id: shop.id, prices: '101__2000' }
          should respond_with(200)
          response_body = JSON.parse(response.body)
          expect(response_body).to be_an_instance_of(Array)
          expect(response_body.count).to eq(2)
        end
      end

      context 'with sort_by filters' do
        context 'highest-score' do
          it 'returns array of products by score' do
            products = [
              create(:available_product, name: 'patator', status: "online", score: 8),
              create(:available_product, name: 'koup-koup', status: "online", score: 8),
              create(:available_product, name: 'tromblon', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 8),
              create(:available_product, name: 'coutelas', status: "online", score: 0),
              create(:available_product, name: 'coutelas', status: "online", score: 2),
              create(:available_product, name: 'coutelas', status: "online", score: 1),
              create(:available_product, name: 'coutelas', status: "online", score: 4),
              create(:available_product, name: 'coutelas', status: "online", score: 2),
              create(:available_product, name: 'coutelas', status: "online", score: 4),
              create(:available_product, name: 'coutelas', status: "online", score: 7),
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products_to_return = products.sort_by!(&:score)

            allow(Product).to receive(:search).and_return(products_to_return.to_a)
            get :index, params: { id: shop.id, sort_by: 'highest-score' }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(15)
            expect(response_body.pluck('id')).to eq(products_to_return.pluck(:id))
          end
        end
        context 'price-asc' do
          it 'returns array of products by price asc' do
            products = [
              create(:available_product, name: 'patator', status: "online", score: 5),
              create(:available_product, name: 'koup-koup', status: "online", score: 5),
              create(:available_product, name: 'tromblon', status: "online", score: 2),
              create(:available_product, name: 'coutelas', status: "online", score: 1)
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products.each_with_index { |p, i| p.references.first.update(base_price: i + 1) }
            products_to_return = products.sort_by! { |p| p.references.first.base_price }

            allow(Product).to receive(:search).and_return(products_to_return.to_a)
            get :index, params: { id: shop.id, sort_by: 'price-asc' }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(4)
            expect(response_body.pluck('id')).to eq(products_to_return.pluck(:id))
          end
        end
        context 'price-desc' do
          it 'returns array of products by price desc' do
            products = [
              create(:available_product, name: 'patator', status: "online", score: 5),
              create(:available_product, name: 'koup-koup', status: "online", score: 5),
              create(:available_product, name: 'tromblon', status: "online", score: 2),
              create(:available_product, name: 'coutelas', status: "online", score: 1)
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products.each_with_index { |p, i| p.references.first.update(base_price: i + 1) }
            products_to_return = products.sort_by! { |p| p.references.first.base_price }.reverse!

            allow(Product).to receive(:search).and_return(products_to_return.to_a)
            get :index, params: { id: shop.id, sort_by: 'price-asc' }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(4)
            expect(response_body.pluck('id')).to eq(products_to_return.pluck(:id))
          end
        end

        context 'newest' do
          it 'returns array of products sorted by created_at' do
            products = [
              create(:available_product, name: 'patator', status: "online"),
              create(:available_product, name: 'koup-koup', status: "online"),
              create(:available_product, name: 'tromblon', status: "online"),
              create(:available_product, name: 'coutelas', status: "online")
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products_to_return = products.each_with_index { |p, i| p.update(created_at: p.created_at - i.days) }

            allow(Product).to receive(:search).and_return(products_to_return.to_a)
            get :index, params: { id: shop.id, sort_by: 'newest' }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(4)
            expect(response_body.pluck('id')).to eq(products_to_return.pluck(:id))
          end
        end

        context 'position' do
          it 'returns array of products sorted by position asc' do
            products = [
              create(:available_product, name: 'patator', status: "online", position: 1),
              create(:available_product, name: 'koup-koup', status: "online", position: 2),
              create(:available_product, name: 'tromblon', status: "online", position: 3),
              create(:available_product, name: 'coutelas', status: "online", position: 4)
            ]
            shop = create(:shop)
            products.each { |prod| prod.update(shop_id: shop.id) }
            products_to_return = products.sort_by!(&:position)

            allow(Product).to receive(:search).and_return(products_to_return.to_a)
            get :index, params: { id: shop.id, sort_by: 'position' }
            should respond_with(200)
            response_body = JSON.parse(response.body)
            expect(response_body).to be_an_instance_of(Array)
            expect(response_body.count).to eq(4)
            expect(response_body.pluck('id')).to eq(products_to_return.pluck(:id))
          end
        end
      end
    end

    context "with invalid params" do
      context "shop_id not a Numeric" do
        it "should returns 400 HTTP Status" do
          get :index, params: { id: 'Xenomorph' }
          should respond_with(400)
          expect(response.body).to eq(Dto::Errors::BadRequest.new('Shop_id is incorrect').to_h.to_json)
        end
      end

      context "shop doesn't exists" do
        it "should returns 404 HTTP Status" do
          id = 1
          Shop.all.each do |shop|
            break if shop.id != id
            id = id + 1
          end
          get :index, params: { id: id }
          should respond_with(404)
          expect(response.body).to eq(Dto::Errors::NotFound.new("Couldn't find Shop with 'id'=#{id}").to_h.to_json)
        end
      end
    end
  end

  describe "POST #create" do
    context "All ok" do
      it "should return 202 HTTP Status with product created" do
        shop = create(:shop)
        create_params = {
          name: "manteau MAC",
          slug: "manteau-mac",
          categoryId: create(:category).id,
          brand: "3sixteen",
          status: "online",
          isService: true,
          sellerAdvice: "pouet",
          shopId: shop.id,
          description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
          variants: [
            {
              basePrice: 379,
              weight: 1,
              quantity: 0,
              imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
              isDefault: false,
              goodDeal: {
                startAt: "17/05/2021",
                endAt: "18/06/2021",
                discount: 20,
              },
              characteristics: [
                {
                  value: "coloris black",
                  name: "color",
                },
                {
                  value: "S",
                  name: "size",
                },
              ],
            },
          ],
        }
        user_shop_employee = create(:shop_employee_user, email: "shop.employee310@ecity.fr")
        user_shop_employee.shop_employee.shops << shop
        user_shop_employee.shop_employee.save
        request.headers["x-client-id"] = generate_token(user_shop_employee)
        job_id = "10aad2e35138aa982e0d848a"
        allow(Dao::Product).to receive(:create_async).and_return(job_id)
        expect(Dao::Product).to receive(:create_async)
        post :create, params: create_params
        should respond_with(202)
        expect(JSON.parse(response.body)["url"]).to eq(ENV["API_BASE_URL"] + api_v1_product_job_status_path(job_id))
      end
    end

    context "Param incorrect" do
      let(:user_shop_employee) { create(:shop_employee_user, email: "shop.employee7@ecity.fr") }

      context "Shop id is missing" do
        it "should return 400 HTTP status" do
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          request.headers["x-client-id"] = generate_token(user_shop_employee)

          post :create, params: create_params

          should respond_with(400)
        end
      end

      context "Shop not found" do
        it "should return 404 HTTP status" do
          shop = create(:shop)
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            shopId: shop.id,
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          user_shop_employee.shop_employee.shops << shop
          user_shop_employee.shop_employee.save
          Shop.destroy_all

          request.headers["x-client-id"] = generate_token(user_shop_employee)

          post :create, params: create_params

          should respond_with(404)
        end
      end

      context "Category id is missing" do
        it "should return 400 HTTP status" do
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            shopId: create(:shop).id,
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }

          request.headers["x-client-id"] = generate_token(user_shop_employee)

          post :create, params: create_params

          should respond_with(400)
        end
      end

      context "Category not found" do
        it "should return 404 HTTP Status" do
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            brand: "3sixteen",
            status: "online",
            categoryId: create(:category).id,
            isService: true,
            sellerAdvice: "pouet",
            shopId: create(:shop).id,
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          Product.all.each do |p|
            p.category_id = nil
            p.save
          end
          Category.delete_all

          request.headers["x-client-id"] = generate_token(user_shop_employee)

          post :create, params: create_params

          should respond_with(404)
        end
      end

      context "Category is dry-fresh group" do
        let(:category) { create(:category, group: "dry-food") }
        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            category = create(:category)
            category.group = "dry-food"
            category.save

            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end
      context "Category is fresh-food group" do
        let(:category) { create(:category, group: "fresh-food") }
        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end
      context "Category is frozen-food group" do
        let(:category) { create(:category, group: "frozen-food") }
        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end
      context "Category is alcohol group" do
        let(:category) { create(:category, group: "alcohol") }

        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end

      context "Category is cosmetic group" do
        let(:category) { create(:category, group: "cosmetic") }

        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end
      context "Category is food group" do
        let(:category) { create(:category, group: "food") }
        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Allergens of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              composition: "Tissu",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("allergens is required")
          end
        end
      end

      context "Category is clothing group" do
        let(:category) { create(:category, group: "clothing") }

        context "Origin of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end

        context "Composition of product is missing" do
          it "should return 400 HTTP Status" do
            create_params = {
              name: "manteau MAC",
              slug: "manteau-mac",
              categoryId: category.id,
              brand: "3sixteen",
              status: "online",
              isService: true,
              sellerAdvice: "pouet",
              shopId: create(:shop).id,
              origin: "France",
              description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
              variants: [
                {
                  basePrice: 379,
                  weight: 1,
                  quantity: 0,
                  imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                  isDefault: false,
                  goodDeal: {
                    startAt: "17/05/2021",
                    endAt: "18/06/2021",
                    discount: 20,
                  },
                  characteristics: [
                    {
                      value: "coloris black",
                      name: "color",
                    },
                    {
                      value: "S",
                      name: "size",
                    },
                  ],
                },
              ],
            }

            request.headers["x-client-id"] = generate_token(user_shop_employee)

            post :create, params: create_params

            should respond_with(400)
            result = JSON.parse(response.body)
            expect(result["detail"]).to eq("origin and composition is required")
          end
        end
      end
    end

    context "Bad authentication" do
      context "x-client-id is missing" do
        it "should return 401 HTTP status" do
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }

          post :create, params: create_params

          should respond_with(401)
        end
      end

      context "User is not a shop employee" do
        it "should return 403 HTTP status" do
          create_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          user_customer_user = create(:customer_user, email: "shop.employee3@ecity.fr")

          request.headers["x-client-id"] = generate_token(user_customer_user)

          post :create, params: create_params

          should respond_with(403)
        end
      end

    end
  end

  describe "PATCH #update" do
    context "All ok" do
      it 'should return 200 HTTP Status with product modified' do
        user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
        reference = create(:reference, base_price: 400)
        product = reference.product
        product.name = "Before MAJ"
        product.status = "submitted"
        product.save

        product_params = {
          name: "After MAJ",
          status: "online",
          variants: [
            {
              id: reference.id,
              basePrice: 300
            }
          ]
        }
        user_shop_employee.shop_employee.shops << product.shop
        user_shop_employee.shop_employee.save

        request.headers["x-client-id"] = generate_token(user_shop_employee)
        patch :update, params: product_params.merge(id: product.id)

        should respond_with(200)
        result = JSON.parse(response.body)
        product.reload
        expect(result["id"]).to eq(product.id)
        expect(result["name"]).to eq(product.name)
        expect(result["name"]).to eq(product_params[:name])
        variant_params_expected = product_params[:variants].find { |variant| variant[:id] == reference.id}
        variant_to_compare = result["variants"].find { |variant| variant["id"] == variant_params_expected[:id]}
        expect(variant_to_compare).not_to be_nil
        expect(variant_to_compare["basePrice"]).to eq(variant_params_expected[:basePrice])
      end

      context "Want to accepted product from citizen" do
        it "should return 200 with product' status updated to offline" do
          user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
          reference = create(:reference, base_price: 400, quantity: 0)
          product = reference.product
          product.name = "Before MAJ"
          product.status = "submitted"
          product.save

          product_params = { status: "online" }

          user_shop_employee.shop_employee.shops << product.shop
          user_shop_employee.shop_employee.save

          request.headers["x-client-id"] = generate_token(user_shop_employee)
          patch :update, params: product_params.merge(id: product.id)

          should respond_with(200)
          result = JSON.parse(response.body)
          product.reload
          expect(result["status"]).to eq("offline")
          expect(product.status).to eq("offline")
        end
      end

      context "Want to change product' status to online (all conditions required are ok)" do
        it "should return 200 with product' status updated to online" do
          user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
          reference = create(:reference, base_price: 400, quantity: 5)
          product = reference.product
          product.name = "Before MAJ"
          product.status = "offline"
          product.save

          product_params = { status: "online" }

          user_shop_employee.shop_employee.shops << product.shop
          user_shop_employee.shop_employee.save

          request.headers["x-client-id"] = generate_token(user_shop_employee)
          patch :update, params: product_params.merge(id: product.id)

          should respond_with(200)
          result = JSON.parse(response.body)
          product.reload
          expect(result["status"]).to eq("online")
          expect(product.status).to eq("online")
        end
      end
    end

    context "Bad authentification" do
      context "No user" do
        it 'should return 401 HTTP Status' do
          user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
          reference = create(:reference)
          product = reference.product
          product_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
              {
                id: reference.id,
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          user_shop_employee.shop_employee.shops << product.shop
          user_shop_employee.shop_employee.save

          patch :update, params: product_params.merge(id: product.id)

          should respond_with(401)
          expect(response.body).to eq(Dto::Errors::Unauthorized.new.to_h.to_json)
        end
      end

      context "User is not a shop employee" do
        it 'should return 403 HTTP Status' do
          user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
          reference = create(:reference)
          product = reference.product
          product_params = {
            name: "manteau MAC",
            slug: "manteau-mac",
            categoryId: create(:category).id,
            brand: "3sixteen",
            status: "online",
            isService: true,
            sellerAdvice: "pouet",
            description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
            variants: [
              {
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
              {
                id: reference.id,
                basePrice: 379,
                weight: 1,
                quantity: 0,
                imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
                isDefault: false,
                goodDeal: {
                  startAt: "17/05/2021",
                  endAt: "18/06/2021",
                  discount: 20,
                },
                characteristics: [
                  {
                    value: "coloris black",
                    name: "color",
                  },
                  {
                    value: "S",
                    name: "size",
                  },
                ],
              },
            ],
          }
          user_shop_employee.shop_employee.shops << product.shop
          user_shop_employee.shop_employee.save

          request.headers["x-client-id"] = generate_token(create(:citizen_user, email: "citizen768@ecity.fr"))
          patch :update, params: product_params.merge(id: product.id)

          should respond_with(403)
          expect(response.body).to eq(Dto::Errors::Forbidden.new.to_h.to_json)
        end
      end
    end

    context "Product not found in shop of shop employee" do
      it 'should return 404 HTTP status' do
        user_shop_employee = create(:shop_employee_user, email: "shop.employee3@ecity.fr")
        reference = create(:reference)
        product = reference.product
        product_params = {
          name: "manteau MAC",
          slug: "manteau-mac",
          categoryId: create(:category).id,
          brand: "3sixteen",
          status: "online",
          isService: true,
          sellerAdvice: "pouet",
          description: "Manteau type Macintosh en tissu 100% coton déperlant sans traitement. Les fibres de coton à fibres extra longues (ELS) sont tissées de manière incroyablement dense - rien de plus. Les fibres ELS sont difficiles à trouver - seulement 2% du coton mondial peut fournir des fibres qui répondent à cette norme.Lorsque le tissu est mouillé, ces fils se dilatent et créent une barrière impénétrable contre l'eau. Le tissu à la sensation au touché, le drapé et la respirabilité du coton avec les propriétés techniques d'un tissu synthétique. Le manteau est doté d'une demi-doublure à imprimé floral réalisée au tampon à la main dans la plus pure tradition indienne.2 coloris: TAN ou BLACK",
          variants: [
            {
              basePrice: 379,
              weight: 1,
              quantity: 0,
              imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
              isDefault: false,
              goodDeal: {
                startAt: "17/05/2021",
                endAt: "18/06/2021",
                discount: 20,
              },
              characteristics: [
                {
                  value: "coloris black",
                  name: "color",
                },
                {
                  value: "S",
                  name: "size",
                },
              ],
            },
            {
              id: reference.id,
              basePrice: 379,
              weight: 1,
              quantity: 0,
              imageUrls: ["https://www.eklecty-city.fr/wp-content/uploads/2018/07/robocop-paul-verhoeven-banner.jpg"],
              isDefault: false,
              goodDeal: {
                startAt: "17/05/2021",
                endAt: "18/06/2021",
                discount: 20,
              },
              characteristics: [
                {
                  value: "coloris black",
                  name: "color",
                },
                {
                  value: "S",
                  name: "size",
                },
              ],
            },
          ],
        }
        user_shop_employee.shop_employee.shops << create(:shop)
        user_shop_employee.shop_employee.save

        request.headers["x-client-id"] = generate_token(user_shop_employee)
        patch :update, params: product_params.merge(id: product.id)

        should respond_with(404)
        expect(response.body).to eq(Dto::Errors::NotFound.new("Couldn't find Product with 'id'=#{product.id} [WHERE \"products\".\"shop_id\" = $1]").to_h.to_json)
      end
    end

  end
end



