name: "Label 'Tyk OK' required"
on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "Tyk OK"
        REQUIRED_LABELS_ANY_DESCRIPTION: "You must manually add the 'Tyk OK' label to the PR after Tyk configuration for all environments in order to be merged."
        BANNED_LABELS: "banned"
